<span id="ebi_logo"> 	  
<p>
WormBase ParaSite is developed by <a href="http://www.ebi.ac.uk">EMBL-EBI</a> and the <a href="http://www.sanger.ac.uk">Wellcome Trust Sanger Institute</a>.  The website is powered by <a href="http://www.ensembl.org">Ensembl</a> software system for the analysis and visualisation of genomic data.  The project is funded by the <a href="http://www.bbsrc.ac.uk">Biotechnology and Biological Sciences Research Council</a> under grant number BB/K020080.
</p>
<p>
<a href="http://www.ebi.ac.uk"> <img align="absmiddle" src="/img/ebi_logo.png" /></a> 
<a style="padding-left:20px" href="http://www.sanger.ac.uk"> <img align="absmiddle" src="/img/sanger_logo.png" /></a>
<a style="padding-left:20px" href="http://www.ensembl.org"><img align="absmiddle" src="/img/empowered.png" /></a>
<a style="padding-left:20px" href="http://www.bbsrc.ac.uk"><img align="absmiddle" src="/img/bbsrc_logo.gif" /></a>
</p>
</span>
