
<div id="homepage-rotator" class="js_panel" style="float:right;position:relative;min-width:125px;min-height:125px;margin-left:20px;margin-bottom:12px" >
	<input type="hidden" value="ImageRotator" class="panel_type">
	<a href="/Brugia_malayi_prjna10729/Info/Index"><img id="homepage-img1" class="homepage-image" src="/i/homepage/brugia_malayi.png" alt="Brugia malayi" title="Brugia malayi.  Image credit: Public Health Image Library (Centers for Disease Control and Prevention)." /></a>
	<a href="/Trichinella_spiralis_prjna12603/Info/Index"><img id="homepage-img2" class="homepage-image" src="/i/homepage/trichinella_spiralis.png" alt="Trichinella spiralis" title="Trichinella spiralis.  Image credit: Dickson Despommier (trichinella.org)." style="display:none" /></a>
	<a href="/Onchocerca_volvulus_prjeb513/Info/Index"><img id="homepage-img3" class="homepage-image" src="/i/homepage/onchocerca_volvulus.png" alt="Onchocerca volvulus" title="Onchocerca volvulus." style="display:none" /></a>
	<a href="/Loa_loa_prjna60051/Info/Index"><img id="homepage-img4" class="homepage-image" src="/i/homepage/loa_loa.png" alt="Loa loa" title="Loa loa.  Image credit: Public Health Image Library (Centers for Disease Control and Prevention)." style="display:none" /></a>
</div>

<p>Parasitic worms (helminths) are responsible for more than a billion human infections globally and have a devastating impact on livestock and agriculture. As international efforts to sequence the genomes of parasitic helminths accelerate, the WormBase groups at EMBL-EBI and Wellcome Trust Sanger Institute have collaborated on the creation of a new resource, WormBase ParaSite, to analyse, store and present information on these genomes. WormBase ParaSite is closely integrated with and complementary to the main <a href="http://www.wormbase.org">WormBase</a> resource, the central focus of which is the model nematode <em>Caenorhabditis elegans</em> and it close relatives.</p>
