
<h2 data-generic-icon="U">What's New</h2>
<p>
	Version: 2.0 (March 2015)
</p>
<p>
	New Genomes
	<ul>
		<li><a href="/Opisthorchis_viverrini_prjna222628/Info/Index"><em>Opisthorchis viverrini</em> (PRJNA222628)</a></li>
		<li><a href="/Pristionchus_exspectatus_prjeb6009/Info/Index"><em>Pristionchus exspectatus</em> (PRJEB6009)</a></li>
		<li><a href="/Fasciola_hepatica_prjeb6687/Info/Index"><em>Fasciola hepatica</em> (PRJEB6687)</a></li>
		<li>Five <em>Steinernema</em> genomes, including <a href="/Steinernema_carpocapsae_prjna202318/Info/Index"><em>Steinernema carpocapsae</em> (PRJNA202318)</a></li>
	</ul>
	Tools
	<ul>
		<li><a href="/biomart/martview">BioMart Data Mining Tool</a></li>
		<li><a href="/Tools/Blast">New BLAST Interface</a></li>
		<li>Updated Comparative Genomics</li>
	</ul>
</p>
