
<h2 data-generic-icon="U">What's New</h2>
<div style="position:relative">
	<div style="float:right;top:12px;right:10px;clear:both" id="img-container">
		<a href="/Steinernema_carpocapsae_prjna202318/Info/Index"><img src="/i/homepage/SCarpo.png" alt="Steinernema carpocapsae emerging from an infected waxworm" title="Steinernema carpocapsae emerging from an infected waxworm (Image Credit: Adler Dillman)" style="border: 1px solid lightgrey; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px;" /></a>
	</div>
	<p>
		Version: 2.0 (March 2015)
	</p>
	<p>
                <span style="font-weight:bold;font-size:1.2em">Tools</span>
                <ul>
                        <li><a href="/biomart/martview">BioMart Data Mining Tool</a></li>
                        <li><a href="/Tools/Blast">New BLAST Interface</a></li>
                        <li>Updated Comparative Genomics</li>
                </ul>
		<span style="font-weight:bold;font-size:1.2em">New Genomes</span>
		<ul>
			<li><a href="/Fasciola_hepatica_prjeb6687/Info/Index"><em>Fasciola hepatica</em> (PRJEB6687)</a></li>
			<li><a href="/Opisthorchis_viverrini_prjna222628/Info/Index"><em>Opisthorchis viverrini</em> (PRJNA222628)</a></li>
			<li><a href="/Pristionchus_exspectatus_prjeb6009/Info/Index"><em>Pristionchus exspectatus</em> (PRJEB6009)</a></li>
			<li>Five <em>Steinernema</em> genomes, including <a href="/Steinernema_carpocapsae_prjna202318/Info/Index"><em>Steinernema carpocapsae</em> (PRJNA202318)</a></li>
		</ul>
	</p>
</div>
