
<h2 data-generic-icon="U">What's New</h2>
<div style="float:right;top:10px;right:10px;padding-bottom:10px;clear:both">
	<a href="/Multi/GeneTree/Image?gt=WBGT00000000120084"><img src="/i/homepage/compara.png" alt="Comparative Genomics - Gene Tree" title="Comparative Genomics - Gene Trees" style="border: 1px solid lightgrey; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px;" /></a>
</div>
<p>
	Version: 1.0 (September 2014)
</p>
<p>
	Genomes
	<ul>
		<li>82 Species</li>
		<li>89 Genomes</li>
	</ul>
	Tools
	<ul>
		<li>Genome Browser</li>
		<li>Comparative Genomics</li>
		<li>BLAST</li>
		<li>Variant Effect Predictor</li>
		<li>Raw Data Downloads</li>
	</ul>
</p>
